title: Meu Site Pessoal
description: >- # Descrição do site
  Bem-vindo ao meu site pessoal, onde compartilho projetos, ideias e insights.
theme: minima

# Outras configurações
markdown: kramdown
highlighter: rouge

# Configurações de URL
url: "https://leitaofilho.github.io"
baseurl: ""

# Configurações do Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Redes sociais
author:
  name: "Seu Nome"
  email: "seuemail@email.com"
  twitter_username: "seutwitter"
  github_username: "leitaofilho"

# SEO
google_analytics: UA-XXXXXXX-X
